services:
  # Web File Browser
  # mkdir filebrowser_data filebrowser_conf && chown -R 1000:1000 filebrowser_data filebrowser_conf
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    restart: unless-stopped
    user: 0:0
    volumes:
      - $HOME:/srv                    # root directory
      - ./filebrowser_data:/database  # filebrowser.db
      - ./filebrowser_conf:/config    # settings.json
    ports:
      - 8300:80

  # Web File Browser, Teminal and Monaco Editor
  cloud-cmd:
    image: coderaiser/cloudcmd
    container_name: cloud-cmd
    restart: always
    ports:
      - 8123:8000
    volumes:
      - /home:/home
    environment:
      - CLOUDCMD_AUTH=true
      - CLOUDCMD_USERNAME=admin
      - CLOUDCMD_PASSWORD=admin
      - CLOUDCMD_THEME=dark
      - CLOUDCMD_EDITOR=deepword
      - CLOUDCMD_CONSOLE=true
      - CLOUDCMD_TERMINAL=true

  # tinyfilemanager:
  #   image: tinyfilemanager/tinyfilemanager:master
  #   container_name: tinyfilemanager
  #   restart: unless-stopped
  #   volumes:
  #     - $HOME:/var/www/html/data
  #   ports:
  #     - 8080:80

  # dufs:
  #   image: sigoden/dufs
  #   container_name: dufs
  #   restart: unless-stopped
  #   ports:
  #   - 5000:5000
  #   volumes:
  #   - $HOME:/data
  #   - ./config.yaml:/config.yaml
  #   command: /data -A # --config /config.yaml

  # goshs:
  #   image: patrickhener/goshs:latest
  #   container_name: goshs
  #   restart: unless-stopped
  #   command: -d /public
  #   volumes:
  #     - $PWD:/pwd
  #   ports:
  #     - 8000:8000
  #   stdin_open: true
  #   tty: true

  # File Synchronization
  file-syncthing:
    image: syncthing/syncthing
    container_name: file-syncthing
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - 8384:8384         # Web UI
    #   - 22000:22000/tcp   # TCP file transfers
    #   - 22000:22000/udp   # QUIC file transfers
    #   - 21027:21027/udp   # Receive local discovery broadcasts
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./syncthing_data:/var/syncthing   # configs
      - $HOME/docker:/sync_data           # src sync data on server
      # - ./backup:/sync_data             # dst sync data on client (mkdir backup && chown -R 1000:1000 backup)
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  # Web Server Index
  # h5ai:
  #   image: awesometic/h5ai
  #   container_name: h5ai
  #   restart: unless-stopped
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/GMT+3
  #     - HTPASSWD=false
  #     - HTPASSWD_USER=admin
  #     - HTPASSWD_PW=admin
  #   volumes:
  #     - $HOME/docker:/h5ai    # public data
  #     - ./h5ai_conf:/config
  #   ports:
  #     - 8889:80

  # FTP/S, SSH/SFTP, WebDAV and S3 server
  # sftpgo:
  #   image: drakkan/sftpgo:edge
  #   container_name: sftpgo
  #   restart: unless-stopped
  #   ports:
  #     - 2022:2022
  #     - 8088:8080